In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
vocab_size=10000

### One Hot 

In [6]:
one_hot_rep=[one_hot(words,vocab_size) for words in sent]

In [8]:
print(one_hot_rep)

[[4671, 1626, 9990, 2131], [4671, 1626, 9990, 3534], [4671, 635, 9990, 5764], [8736, 2338, 2195, 86, 3977], [8736, 2338, 2195, 86, 7487], [9884, 4671, 3158, 9990, 2683], [3071, 3265, 1412, 86]]


### Word Embedding 

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embed_doc=pad_sequences(one_hot_rep,maxlen=sent_length,padding='pre')
embed_doc

array([[   0,    0,    0,    0, 4671, 1626, 9990, 2131],
       [   0,    0,    0,    0, 4671, 1626, 9990, 3534],
       [   0,    0,    0,    0, 4671,  635, 9990, 5764],
       [   0,    0,    0, 8736, 2338, 2195,   86, 3977],
       [   0,    0,    0, 8736, 2338, 2195,   86, 7487],
       [   0,    0,    0, 9884, 4671, 3158, 9990, 2683],
       [   0,    0,    0,    0, 3071, 3265, 1412,   86]], dtype=int32)

In [12]:
dim=15

In [15]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(embed_doc))

[[[ 0.04503194  0.04829151 -0.0465999   0.04168731 -0.01805345
   -0.02439202  0.00165112 -0.02778335 -0.00993222 -0.01297732]
  [ 0.04503194  0.04829151 -0.0465999   0.04168731 -0.01805345
   -0.02439202  0.00165112 -0.02778335 -0.00993222 -0.01297732]
  [ 0.04503194  0.04829151 -0.0465999   0.04168731 -0.01805345
   -0.02439202  0.00165112 -0.02778335 -0.00993222 -0.01297732]
  [ 0.04503194  0.04829151 -0.0465999   0.04168731 -0.01805345
   -0.02439202  0.00165112 -0.02778335 -0.00993222 -0.01297732]
  [ 0.04934324  0.02349344  0.0115353   0.02783582 -0.00747352
   -0.03799548  0.0165594  -0.02669687  0.01711288 -0.01407626]
  [-0.03288467  0.03839921  0.04319886  0.0304342   0.03673379
   -0.04409513 -0.00738481  0.0015053  -0.0262861   0.0113216 ]
  [-0.01383964  0.01284656 -0.02381095 -0.04684351 -0.03541875
   -0.01319085  0.02773515  0.00310599  0.028948    0.04120063]
  [-0.0258415   0.00361742  0.03224706 -0.02007334  0.00052053
   -0.04802662  0.01828802  0.02363335 -0.000232

In [19]:
embed_doc[0]

array([   0,    0,    0,    0, 4671, 1626, 9990, 2131], dtype=int32)

In [27]:
model.predict(embed_doc)[0][4,:]

array([ 0.04934324,  0.02349344,  0.0115353 ,  0.02783582, -0.00747352,
       -0.03799548,  0.0165594 , -0.02669687,  0.01711288, -0.01407626],
      dtype=float32)